INSERT INTO forms (id, form_type, form_desc, active) VALUES
(DEFAULT, '3', 'Initial statement of beneficial ownership of securities', true),
(DEFAULT, '4', 'Statement of changes in beneficial ownership of securities', true),
(DEFAULT, '6-K', 'Report of foreign private issuer', true),
(DEFAULT, '8-K', 'Current report', true),
(DEFAULT, '10-K', 'Annual report', true),
(DEFAULT, '10-Q', 'Quarterly report', true),
(DEFAULT, 'SC 13F', 'Quarterly report of institutional investment holdings', true),
(DEFAULT, 'SC 13D', 'Report of acquisition of active beneficial ownership of more than 5 percent', true),
(DEFAULT, 'SC 13G', 'Report of acquisition of passive beneficial ownership of more than 5 percent', true),
(DEFAULT, 'F-1', 'Statement of registration of securities by a foreign issuer', true),
(DEFAULT, 'S-1', 'Statement of registration of securities', true),
(DEFAULT, 'S-3', 'Short-form statement of registration of securities', true),
(DEFAULT, 'S-4', 'Statement of registration of securities related to merger or acquisition', true),
(DEFAULT, 'S-8', 'Statement of registration of securities as part of an employee benefit plan', true),
(DEFAULT, 'SD', 'Specialized disclosure report', true),
(DEFAULT, 'D', 'Notice of exempt offering of securities', true);
